data("iris")
sepalLength <- iris$Sepal.Length
barplot(sepalLength,xlab="SepalLength",col="red")
barplot(sepalLength,ylab="SepalLength",horiz = TRUE,col="yellow")
sepalWidth <- head(iris$Sepal.Width)
sepalLength <- head(iris$Sepal.Length)
petalLength <- head(iris$Petal.Length)
petalWidth <- head(iris$Petal.Width)
x <- c(sepalLength, sepalWidth, petalLength, petalWidth)
labels <- c("sepalLength", "sepalWidth", "petalLength", "petalWidth")
pie(x,labels,main = "iris pie chart",col=rainbow(length(x)))
hist(sepalLength,col="cyan")
M1<-read.csv("E:\\SKASC\\R\\Knn.csv")
boxplot(M1[,2:3],col="blue")
plot(M1$Height ,M1$Weight, type = "l",col="cyan")
plot(M1$Height ,M1$Weight, type = "p",col="blue")
plot(M1$Height ,M1$Weight, type = "b",col="red")
plot(M1$Height ,M1$Weight, type = "h",col="yellow")
